import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/styles/globals.css";

const cascadiaCode = localFont({
  src: [
    {
      path: '/fonts/CascadiaCode.ttf',
      style: 'normal',
    },
  ],
  variable: '--font-cascadia',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cascadiaCode.className} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
